"""
plot_momentum_comparison.py
===========================
Loads per-method momentum .npz files and draws a 3-panel comparison figure:
    CKMPM  |  MLS-MPM  |  Basic MPM

Each panel shows:
    - Cube 0  (red)
    - Cube 1  (orange)
    - Total   (blue, should stay ~0)

Usage:
    python plot_momentum_comparison.py

Expected input files (generated by running each solver):
    output/colliding_cubes_momentum_mlsmpm.npz    ← from MLS-MPM test
    output/colliding_cubes_momentum_basic.npz     ← from basic-MPM test
    output/colliding_cubes_momentum_ckmpm.npz     ← from CKMPM post-processor (see below)

CKMPM note:
    CKMPM outputs .bgeo particle files.  Run the companion script
    ckmpm_momentum_from_bgeo.py  to convert them into the same .npz format.
    If the CKMPM .npz is not found, that panel is skipped.
"""

import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "output")
OUT_FIG = os.path.join(OUT_DIR, "colliding_cubes_momentum_comparison.png")

def first_existing_path(candidates):
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


SOURCES = [
    (
        "CKMPM",
        [
            os.path.join(OUT_DIR, "colliding_cubes_momentum_ckmpm.npz"),
        ],
        "#8e44ad",
    ),
    (
        "MLS-MPM",
        [
            os.path.join(OUT_DIR, "colliding_cubes_momentum_mlsmpm.npz"),
            os.path.normpath(
                os.path.join(HERE, "..", "..", "MLS_MPM_clone", "tests", "output",
                             "colliding_cubes_momentum_mlsmpm.npz")
            ),
        ],
        "#27ae60",
    ),
    (
        "Basic MPM",
        [
            os.path.join(OUT_DIR, "colliding_cubes_momentum_basic.npz"),
        ],
        "#e67e22",
    ),
]

available = []
for label, candidates, color in SOURCES:
    path = first_existing_path(candidates)
    if path is not None:
        available.append((label, path, color))

if not available:
    raise FileNotFoundError(
        "No momentum .npz files found in output/.\n"
        "Run each solver first:\n"
        "  python MLS_MPM_clone/tests/test_colliding_cubes.py\n"
        "  python mpm-base/3d/simulator_3d_colliding_squares.py\n"
        "  (CKMPM: build + run, then ckmpm_momentum_from_bgeo.py)"
    )

n_panels = len(available)
fig, axes = plt.subplots(1, n_panels, figsize=(5.5 * n_panels, 4.5), sharey=True)
if n_panels == 1:
    axes = [axes]

for ax, (label, path, accent) in zip(axes, available):
    d = np.load(path)
    t       = d["times"]
    px0     = d["px0"]
    px1     = d["px1"]
    px_tot  = d["px_total"]

    ax.plot(t, px0,    lw=1.8, color="#e74c3c", label="Cube 0")
    ax.plot(t, px1,    lw=1.8, color="#f39c12", label="Cube 1")
    ax.plot(t, px_tot, lw=1.8, color="#2980b9", label="Total")
    ax.axhline(0, color="k", ls="--", lw=0.8)

    # annotate residual drift
    drift = float(np.max(np.abs(px_tot)))
    ax.text(0.97, 0.05, f"|Δp_total|_max = {drift:.2e} kg·m/s",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=8, color="#2980b9",
            bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="#2980b9", alpha=0.7))

    ax.set_title(label, fontsize=13, fontweight="bold", color=accent)
    ax.set_xlabel("Time (s)")
    ax.grid(True, alpha=0.3)

axes[0].set_ylabel("X-Component of Linear Momentum\n(kg · m/s)")

# shared legend on the right
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc="upper right", ncol=1, framealpha=0.9)

fig.suptitle("Linear Momentum Conservation – Colliding Cubes\n(3 MPM Solvers)",
             fontsize=13, y=1.02)
fig.tight_layout()
fig.savefig(OUT_FIG, dpi=150, bbox_inches="tight")
plt.close(fig)
print(f"Saved → {OUT_FIG}")
